import { CategoryBundle } from "../types";
import categoryData from './data.json'

// fetch status
const FETCH_STATUS = {
  IDLE: 0,
  IN_PROGRESS: 1,
  SUCCESS: 2,
  FAILED: 3,
};

// state of category bundle
const CATEGORY_BUNDLE_STATE = {
  FETCH_CATEGORIES: 0,
  ADD_WIDGET_TO_CATEGORY: 1,
  REMOVE_WIDGET_FROM_CATEGORY: 2,
  SEARCH_WIDGET: 3,
};

// actions
const CATEGORY_ACTIONS = {
  FETCH_CATEGORIES_REQUEST: "FETCH_CATEGORIES_REQUEST",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "FETCH_CATEGORIES_FAILED",
  ADD_WIDGET_SUCCESS: "ADD_WIDGET_SUCCESS",
  REMOVE_WIDGET_SUCCESS: "REMOVE_WIDGET_SUCCESS",
  SEARCH_WIDGET_SUCCESS: "SEARCH_WIDGET_SUCCESS",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES"
};


const INITIAL_CATEGORY_BUNDLE_DATA: CategoryBundle = {
  categories: categoryData,
  fetchStatus: FETCH_STATUS.IDLE,
  categoryBundleState: CATEGORY_BUNDLE_STATE.FETCH_CATEGORIES,
}

export { FETCH_STATUS, CATEGORY_BUNDLE_STATE, CATEGORY_ACTIONS, INITIAL_CATEGORY_BUNDLE_DATA };
